repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '\.(jpg|jpeg|png|gif|bmp|tiff|svg|pdf|xls|xlsx)$'
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos
