---
- block:
    - name: Install homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/Cellar

    - name: Add third-pirty repositories for homebrew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: Install packages using homebrew
      community.general.homebrew:
        name: "{{ homebrew_packages }}"
        state: present

    - name: Install cask packages using homebrew
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_apps }}"
        state: present

  when: ansible_distribution == 'MacOSX'
  become: no
