---
- block:
    - name: Install homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      args:
        creates: /usr/local/Cellar

    - name: Add third-pirty repositories for homebrew
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: Install packages using homebrew
      homebrew:
        name: "{{ homebrew_packages }}"
        state: present

    - name: Install cask packages using homebrew
      homebrew_cask:
        name: "{{ homebrew_cask_apps }}"
        state: present

  when: ansible_distribution == 'MacOSX'
  become: no
